# Challenge 1 - T-test

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_re`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](https://researchbasics.education.uconn.edu/t-test/) and [this Quora](https://www.quora.com/What-is-the-difference-between-a-paired-and-unpaired-t-test). Make sure you understand when to use which type of t-test.

In [1]:
# Import libraries

import pandas as pd

#### Import dataset

In this challenge we will work on the Pokemon dataset you have used last week. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.).

In [2]:
# Import dataset

pokemon = pd.read_csv("../data/Pokemon.csv")

pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

In [ ]:
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html
from scipy.stats import ttest_ind

# H0: Two independent samples have identical average (expected) values. mu1 = mu2
# Ha: Means are different

# The default test assumes same variance. I will remove this assumption. (Welch's t-test)

def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    results = {}

    for feature in features:
        
        # two sided
        results[feature] = float(ttest_ind(s1[feature], s2[feature], equal_var = False).pvalue)
        
    return results

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [25]:
legendary = pokemon.loc[pokemon.Legendary == True]
non_legendary = pokemon.loc[pokemon.Legendary == False]

t_test = t_test_features(legendary, non_legendary)

display(t_test)

{'HP': 1.0026911708035294e-13,
 'Attack': 2.520372449236657e-16,
 'Defense': 4.8269984949193406e-11,
 'Sp. Atk': 1.5514614112239797e-21,
 'Sp. Def': 2.294932786405293e-15,
 'Speed': 1.0490163118824546e-18,
 'Total': 9.35795433595745e-47}

In [30]:
pokemon.groupby("Legendary")[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']].mean()

,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total
Legendary,,,,,,,
False,67.182313,75.669388,71.559184,68.454422,68.892517,65.455782,417.213605
True,92.738462,116.676923,99.661538,122.184615,105.938462,100.184615,637.384615

#### From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

In [ ]:
# Through the hypothesis testing each feature of the pokemons,
# we verify that all of the p-values are inferior to 0.05, which
# indicate that there is significant difference between legendary and non-legendary
# pokemons. We can confidently reject the null hypothesis. 

# Additionally, the means of all of the features are higher for legendary pokemons,
# which indicates they are significantly stronger/better in all of the characteristics.

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [41]:
gen_1 = pokemon.loc[pokemon.Generation==1]
gen_2 = pokemon.loc[pokemon.Generation==2]

t_test_features(gen_1, gen_2)

{'HP': 0.14551697834219637,
 'Attack': 0.24721958967217708,
 'Defense': 0.5677711011725426,
 'Sp. Atk': 0.12332165977104396,
 'Sp. Def': 0.18829872292645733,
 'Speed': 0.0023926593731213447,
 'Total': 0.5631377907941677}

In [44]:
ttest_ind(gen_1["Speed"], gen_2["Speed"], equal_var=False)

TtestResult(statistic=np.float64(3.069594374071931), pvalue=np.float64(0.0023926593731213447), df=np.float64(237.4796500591415))

#### What conclusions can you make?

In [46]:
# I performed an independent t-test between gen 1 and gen 2 pokemons. 
# The only feature that has a p-value < 0.05 is Speed. In that case, we can say that gen 1 pokemons
# and gen 2 pokemons, which means that there are a significant statistical difference between the two groups.
# For speed we can reject the null hypotesis.
# Considering the direction, the t-statistic is approximately 3, which means that pokemons from generation 1
# have considerably higher speed than gen 2. 

# For all of the other attributes of the pokemons, there are no significant statistical difference and we cannot
# reject the null hypothesis.

#### Compare pokemons who have single type vs those having two types.

In [65]:
two_types = pokemon.loc[(~pokemon["Type 1"].isnull()) & (~pokemon["Type 2"].isnull()) ]
single_type = pokemon.loc[(~pokemon["Type 1"].isnull()) & (pokemon["Type 2"].isnull())]

print(two_types.shape)
print(single_type.shape)

t_test_features(two_types, single_type)

(414, 13)
(386, 13)

{'HP': 0.11314389855379418,
 'Attack': 0.00014932578145948315,
 'Defense': 2.7978540411514703e-08,
 'Sp. Atk': 0.00013876216585667926,
 'Sp. Def': 0.00010730610934512794,
 'Speed': 0.024217032818190893,
 'Total': 1.1157056505230019e-07}

In [68]:
print(two_types['Total'].mean())
print(single_type['Total'].mean())

456.6280193236715
412.01554404145077

#### What conclusions can you make?

In [ ]:
# I perform an Independent T-test between single type pokemons (N = 386) and two types pokemons (N = 414). 
#
# Key findings:
# 1. HP: The p-value for HP is greater than 0.05, which means there is a  NO significant statistical difference
# between the HP from pokemons with two types and one type pokemons. And in that case we cannot reject
# the null hypothesis.
#
# 2. Attack, Defense, Sp. Atk, Sp. Def, Speed and Total: 
# For those characteristics, the p-value where inferior to 0.05, which means that there is 
# a significant difference between the pokemons from only one type and the ones with two types.
# Considering the direction, the means of the Total for both categories revealed that two type 
# pokemons are stronger on all of the present characteristics (Attack, Defense, Sp. Atk, Sp. Def, Speed and Total).

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [70]:
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html
from scipy.stats import ttest_rel

print("Attack vs. Defense")
print(pokemon.Attack.shape)
display(ttest_rel(pokemon["Attack"], pokemon["Defense"]))

print("Sp. Atk vs. Sp. Def")
print(pokemon["Sp. Atk"].shape)
ttest_rel(pokemon["Sp. Atk"], pokemon["Sp. Def"])

Attack vs. Defense
(800,)

TtestResult(statistic=np.float64(4.325566393330478), pvalue=np.float64(1.714030347935858e-05), df=np.int64(799))

Sp. Atk vs. Sp. Def
(800,)

TtestResult(statistic=np.float64(0.853986188453353), pvalue=np.float64(0.3933685997548119), df=np.int64(799))

#### What conclusions can you make?

In [71]:
# I run a dependent ttest between Attack and Defense (N = 800)
# Key Findings: The p-value is inferior to 0.05, which indicates that there is statistically significant
# difference between Attack and Defence. 
# Regarding the direction, the t-statistics is approximately 4.3, which indicates that the mean pokemon's attack
# is much larger than its defence, in general.

# Considering the dependent ttest between Attack Speed (Sp. Atk) and Defense Speed (Sp. Def) (N=800)
# Key findings: The p-value is approximately 0.4, which indicates that there is NO significant difference
# between the speeds of attack and defense.

# Overall these tests indicate that while there is no significant difference in the attack and defense speeds,
# the game is biased towards Attack.