# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import pandas as pd
import numpy as np
from scipy.stats import trim_mean, mode, skew, gaussian_kde, pearsonr, spearmanr, beta
from statsmodels.stats.weightstats import ztest as ztest

from scipy.stats import ttest_ind, norm, t
from scipy.stats import f_oneway
from scipy.stats import sem

# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents

In [14]:
# Run this code:
salaries = pd.read_csv('../data/Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [15]:
salaries.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

In [24]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33183 entries, 0 to 33182
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               33183 non-null  object
 1   Job Titles         33183 non-null  object
 2   Department         33183 non-null  object
 3   Full or Part-Time  33183 non-null  object
 4   Salary or Hourly   33183 non-null  object
 5   Typical Hours      8022 non-null   float64
 6   Annual Salary      25161 non-null  float64
 7   Hourly Rate        8022 non-null   float64
dtypes: float64(3), object(5)
memory usage: 2.0+ MB

In [17]:
salaries[['Job Titles', 'Salary or Hourly']].head()

                               Job Titles Salary or Hourly
0                                SERGEANT           Salary
1  POLICE OFFICER (ASSIGNED AS DETECTIVE)           Salary
2                CHIEF CONTRACT EXPEDITER           Salary
3                       CIVIL ENGINEER IV           Salary
4             TRAFFIC CONTROL AIDE-HOURLY           Hourly

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [20]:
# Filtering out only workers paid on an hourly basis:

hourly_df = salaries[salaries['Salary or Hourly'] == 'Hourly']
hourly_df

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86
6,"ABBATACOLA, ROBERT J",ELECTRICAL MECHANIC,AVIATION,F,Hourly,40.0,NaN,46.10
7,"ABBATE, JOSEPH L",POOL MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40.0,NaN,35.60
10,"ABBOTT, BETTY L",FOSTER GRANDPARENT,FAMILY & SUPPORT,P,Hourly,20.0,NaN,2.65
18,"ABDULLAH, LAKENYA N",CROSSING GUARD,OEMC,P,Hourly,20.0,NaN,17.68
...,...,...,...,...,...,...,...,...
33164,"ZUREK, FRANCIS",ELECTRICAL MECHANIC,OEMC,F,Hourly,40.0,NaN,46.10
33168,"ZWARYCZ MANN, IRENE A",CROSSING GUARD,OEMC,P,Hourly,20.0,NaN,17.68
33169,"ZWARYCZ, THOMAS J",POOL MOTOR TRUCK DRIVER,WATER MGMNT,F,Hourly,40.0,NaN,35.60
33174,"ZYGADLO, JOHN P",MACHINIST (AUTOMOTIVE),GENERAL SERVICES,F,Hourly,40.0,NaN,46.35
33175,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,F,Hourly,40.0,NaN,48.85

In [ ]:
# Checking actual hourly wages:

wages = hourly_df['Hourly Rate']
wages

4        19.86
6        46.10
7        35.60
10        2.65
18       17.68
         ...
33164    46.10
33168    17.68
33169    35.60
33174    46.35
33175    48.85
Name: Hourly Rate, Length: 8022, dtype: float64

In [ ]:
# Hypotheses definition:

#H0: mean wage of all hourly workers is $30/hour
#H1: mean wage of all hourly workers differs from $30

from scipy import stats

t_stat, p_value = stats.ttest_1samp(wages, 30)   # only hourly wages used (not all wages)

# We use a one-sample t-test because we are comparing the mean of a single sample (hourly wages)
# against a known (i.e. to be tested via H0) theoretical population mean ($30), and the population standard deviation is unknown.

In [28]:
# Comparing with p-value:

alpha = 1-0.95

if p_value < alpha:
    print("Reject H0")
else:
    print("Do not reject H0")

Reject H0

In [ ]:
# So, do we have enough evidence to reject H₀ (i.e, mean = 30)?

# Yes, given that p_value < alpha = 0.05. In other words, there is sufficient statistical evidence to conclude that the average hourly wage is significantly different from $30.

# Challenge 3 - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [38]:
from scipy.stats import sem
from scipy import stats

mean = wages.mean()
standard_error = stats.sem(wages)
degrees_freedom = len(wages) - 1

confidence_interval = stats.t.interval(0.95, df=degrees_freedom, loc=mean, scale=standard_error)
print(f"The 95% Confidence Interval is: {(confidence_interval)}")

#Below is the computed confidence interval

The 95% Confidence Interval is: (np.float64(32.52345834488425), np.float64(33.05365708767623))

In [36]:
type(confidence_interval)

tuple

In [ ]:
# Cleaning up formatting:
# Unpacking Confidence Interval (a tuple) and rounding lower and upper bounds to 2 decimal places:

lower, upper = confidence_interval
print(f"The 95% Confidence Interval is: ({lower:.2f}, {upper:.2f})")

The 95% Confidence Interval is: (32.52, 33.05)

# Challenge 4 - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [ ]:
# Your code here