# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import pandas as pd
import numpy as np
import scipy.stats as st
from scipy.stats import trim_mean, mode, skew, gaussian_kde, pearsonr, spearmanr, beta
from statsmodels.stats.weightstats import ztest as ztest

from scipy.stats import ttest_ind, norm, t
from scipy.stats import f_oneway
from scipy.stats import sem

# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents

In [2]:
# Run this code:
salaries = pd.read_csv(r'../data/Current_Employee_Names__Salaries__and_Position_Titles.csv')
df_salaries = salaries.copy()

Examine the `salaries` dataset using the `head` function below.

In [3]:
# Your code here

df_salaries.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

In [4]:
df_salaries.info

<bound method DataFrame.info of                         Name                              Job Titles  \
0          AARON,  JEFFERY M                                SERGEANT
1            AARON,  KARINA   POLICE OFFICER (ASSIGNED AS DETECTIVE)
2        AARON,  KIMBERLEI R                CHIEF CONTRACT EXPEDITER
3        ABAD JR,  VICENTE M                       CIVIL ENGINEER IV
4          ABASCAL,  REECE E             TRAFFIC CONTROL AIDE-HOURLY
...                      ...                                     ...
33178  ZYLINSKA,  KATARZYNA                           POLICE OFFICER
33179     ZYMANTAS,  LAURA C                          POLICE OFFICER
33180      ZYMANTAS,  MARK E                          POLICE OFFICER
33181    ZYRKOWSKI,  CARLO E                          POLICE OFFICER
33182   ZYSKOWSKI,  DARIUSZ                  CHIEF DATA BASE ANALYST

             Department Full or Part-Time Salary or Hourly  Typical Hours  \
0                POLICE                 F           Salary            NaN
1                POLICE                 F           Salary            NaN
2      GENERAL SERVICES                 F           Salary            NaN
3           WATER MGMNT                 F           Salary            NaN
4                  OEMC                 P           Hourly           20.0
...                 ...               ...              ...            ...
33178            POLICE                 F           Salary            NaN
33179            POLICE                 F           Salary            NaN
33180            POLICE                 F           Salary            NaN
33181            POLICE                 F           Salary            NaN
33182              DoIT                 F           Salary            NaN

       Annual Salary  Hourly Rate
0           101442.0          NaN
1            94122.0          NaN
2           101592.0          NaN
3           110064.0          NaN
4                NaN        19.86
...              ...          ...
33178        72510.0          NaN
33179        48078.0          NaN
33180        90024.0          NaN
33181        93354.0          NaN
33182       115932.0          NaN

[33183 rows x 8 columns]>

In [5]:
df_salaries.describe()

       Typical Hours  Annual Salary  Hourly Rate
count    8022.000000   25161.000000  8022.000000
mean       34.507604   86786.999790    32.788558
std         9.252077   21041.354602    12.112573
min        10.000000    7200.000000     2.650000
25%        20.000000   76266.000000    21.200000
50%        40.000000   90024.000000    35.600000
75%        40.000000   96060.000000    40.200000
max        40.000000  300000.000000   109.000000

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [6]:
# Your code here

# Import the function from Scipy
from scipy.stats import trim_mean, mode, skew, gaussian_kde, pearsonr, spearmanr, beta
from statsmodels.stats.weightstats import ztest as ztest
from scipy.stats import ttest_ind, norm, t
from scipy.stats import f_oneway
from scipy.stats import sem

# Here we create the test sample, from the given Dataframe : [Salarly or Hourly == Hourly] & [Hourly Rate]

df_HourlyRate = df_salaries[df_salaries['Salary or Hourly']=='Hourly']['Hourly Rate']

# My hypothesis is that the Hourly rate is significantly different from 30$

result = st.ttest_1samp(df_HourlyRate,30)

print(result.pvalue)
print(result.statistic)
print(result.df)

if result.pvalue < 0.05 :
    print(f"We reject the Hypothesis")
else:
    print(f"Hypothesis is Accepted!")

4.323024048623005e-92
20.6198057854942
8021
We reject the Hypothesis

In [7]:
df_HourlyRate.index

Index([    4,     6,     7,    10,    18,    19,    21,    24,    26,    33,
       ...
       33149, 33150, 33156, 33158, 33161, 33164, 33168, 33169, 33174, 33175],
      dtype='int64', length=8022)

# Challenge 3 - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [8]:
df_HourlyRate.head()

4     19.86
6     46.10
7     35.60
10     2.65
18    17.68
Name: Hourly Rate, dtype: float64

In [9]:
# Your code here
# Taken degree of freedom value is result.df
dfTaken = result.df

# Taken Mean of the sample is the result.statistic
meanTaken = result.statistic

#mean of the Hourly rate column
mean_hourlyrate = df_HourlyRate.mean()
print(mean_hourlyrate)

# First we caluculate the standard error of the mean using sem
meanError = st.sem(df_HourlyRate,ddof=1)
print(meanError)

# now based on the above informatino we do the 
confiInter = st.t.interval(0.95,(len(df_HourlyRate)-1),loc=mean_hourlyrate,scale=meanError)
print(confiInter)

32.78855771628024
0.1352368565101596
(np.float64(32.52345834488425), np.float64(33.05365708767623))

# Challenge 4 - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [ ]:
""" lista = []
for size in range(5,300):
    x_size = df_HourlyRate.sample(size)
    lista.append(round(x_size.mean(),4))
lista """

[np.float64(29.766),
 np.float64(33.17),
 np.float64(39.5043),
 np.float64(26.2362),
 np.float64(35.8556),
 np.float64(28.251),
 np.float64(32.2364),
 np.float64(33.7192),
 np.float64(32.5562),
 np.float64(31.0321),
 np.float64(32.8547),
 np.float64(32.9394),
 np.float64(34.2324),
 np.float64(33.9961),
 np.float64(29.6274),
 np.float64(29.391),
 np.float64(31.5133),
 np.float64(33.3432),
 np.float64(31.3674),
 np.float64(36.7425),
 np.float64(34.1316),
 np.float64(27.3727),
 np.float64(33.2081),
 np.float64(35.4443),
 np.float64(34.581),
 np.float64(34.206),
 np.float64(33.1339),
 np.float64(36.4106),
 np.float64(32.0855),
 np.float64(33.1085),
 np.float64(33.1517),
 np.float64(29.0119),
 np.float64(30.0619),
 np.float64(36.3097),
 np.float64(33.2887),
 np.float64(35.1268),
 np.float64(32.5266),
 np.float64(33.1152),
 np.float64(34.3116),
 np.float64(30.2541),
 np.float64(31.684),
 np.float64(32.9635),
 np.float64(31.4219),
 np.float64(32.0377),
 np.float64(29.2631),
 np.float64(34.0722),
 np.float64(31.2825),
 np.float64(33.3596),
 np.float64(32.7702),
 np.float64(31.3911),
 np.float64(34.8289),
 np.float64(31.0402),
 np.float64(32.7435),
 np.float64(32.1307),
 np.float64(32.3698),
 np.float64(32.9465),
 np.float64(33.4148),
 np.float64(33.4034),
 np.float64(31.7341),
 np.float64(30.8453),
 np.float64(31.5132),
 np.float64(34.2529),
 np.float64(32.0057),
 np.float64(34.3685),
 np.float64(34.0455),
 np.float64(32.9221),
 np.float64(31.1537),
 np.float64(33.3869),
 np.float64(33.5179),
 np.float64(32.5189),
 np.float64(32.0155),
 np.float64(33.4367),
 np.float64(33.2709),
 np.float64(31.3569),
 np.float64(31.1946),
 np.float64(32.2638),
 np.float64(30.5148),
 np.float64(34.1976),
 np.float64(31.0251),
 np.float64(35.0446),
 np.float64(30.9536),
 np.float64(33.2191),
 np.float64(35.8367),
 np.float64(34.3085),
 np.float64(32.3525),
 np.float64(32.5338),
 np.float64(32.4221),
 np.float64(31.2108),
 np.float64(32.017),
 np.float64(32.5057),
 np.float64(33.5844),
 np.float64(31.9609),
 np.float64(33.0187),
 np.float64(34.4699),
 np.float64(32.1642),
 np.float64(34.2345),
 np.float64(34.3179),
 np.float64(30.6821),
 np.float64(32.8395),
 np.float64(33.7443),
 np.float64(32.0789),
 np.float64(34.7548),
 np.float64(32.0116),
 np.float64(32.1255),
 np.float64(33.6551),
 np.float64(32.2335),
 np.float64(32.1972),
 np.float64(32.3708),
 np.float64(34.05),
 np.float64(34.6451),
 np.float64(32.99),
 np.float64(33.9881),
 np.float64(33.0715),
 np.float64(31.2648),
 np.float64(32.6148),
 np.float64(32.1852),
 np.float64(34.4071),
 np.float64(33.585),
 np.float64(31.4244),
 np.float64(33.1019),
 np.float64(32.6586),
 np.float64(33.8306),
 np.float64(33.2214),
 np.float64(32.1296),
 np.float64(32.1786),
 np.float64(32.6017),
 np.float64(34.9775),
 np.float64(33.0617),
 np.float64(33.2987),
 np.float64(32.4447),
 np.float64(33.5934),
 np.float64(31.6411),
 np.float64(32.2775),
 np.float64(33.4622),
 np.float64(33.0166),
 np.float64(31.4378),
 np.float64(34.0662),
 np.float64(33.9551),
 np.float64(35.6729),
 np.float64(33.4017),
 np.float64(32.9761),
 np.float64(34.9267),
 np.float64(33.1014),
 np.float64(32.5078),
 np.float64(33.3772),
 np.float64(34.6197),
 np.float64(32.1321),
 np.float64(35.2773),
 np.float64(32.2884),
 np.float64(34.0047),
 np.float64(31.3538),
 np.float64(32.2297),
 np.float64(32.6706),
 np.float64(33.5704),
 np.float64(33.9255),
 np.float64(35.0849),
 np.float64(33.284),
 np.float64(33.437),
 np.float64(33.695),
 np.float64(32.963),
 np.float64(32.0812),
 np.float64(33.6989),
 np.float64(33.5693),
 np.float64(33.8632),
 np.float64(33.0834),
 np.float64(32.6858),
 np.float64(32.6577),
 np.float64(33.4992),
 np.float64(33.2394),
 np.float64(32.6338),
 np.float64(32.8062),
 np.float64(30.011),
 np.float64(34.8793),
 np.float64(33.6469),
 np.float64(31.9544),
 np.float64(33.3602),
 np.float64(31.7979),
 np.float64(33.6766),
 np.float64(32.2149),
 np.float64(33.3307),
 np.float64(34.3977),
 np.float64(32.0117),
 np.float64(32.0384),
 np.float64(32.1758),
 np.float64(32.5352),
 np.float64(32.6481),
 np.float64(32.7131),
 np.float64(32.222),
 np.float64(33.0257),
 np.float64(33.2059),
 np.float64(32.9184),
 np.float64(31.2873),
 np.float64(32.1619),
 np.float64(33.7113),
 np.float64(31.6491),
 np.float64(31.8822),
 np.float64(32.7653),
 np.float64(32.1838),
 np.float64(34.3914),
 np.float64(35.1251),
 np.float64(33.054),
 np.float64(31.7965),
 np.float64(31.4735),
 np.float64(32.6076),
 np.float64(33.755),
 np.float64(32.5412),
 np.float64(32.6377),
 np.float64(33.0933),
 np.float64(32.9061),
 np.float64(32.9103),
 np.float64(34.1762),
 np.float64(32.7065),
 np.float64(32.4931),
 np.float64(32.5787),
 np.float64(32.5316),
 np.float64(32.6338),
 np.float64(33.8829),
 np.float64(32.8643),
 np.float64(31.1921),
 np.float64(32.2871),
 np.float64(32.5836),
 np.float64(32.688),
 np.float64(33.9926),
 np.float64(31.2812),
 np.float64(32.0011),
 np.float64(32.4231),
 np.float64(31.8561),
 np.float64(32.5727),
 np.float64(33.8638),
 np.float64(31.8403),
 np.float64(33.4714),
 np.float64(32.1631),
 np.float64(34.0178),
 np.float64(31.8586),
 np.float64(32.3859),
 np.float64(33.3712),
 np.float64(33.5563),
 np.float64(32.2368),
 np.float64(31.749),
 np.float64(33.3992),
 np.float64(32.4201),
 np.float64(32.6691),
 np.float64(32.5682),
 np.float64(33.4628),
 np.float64(32.0841),
 np.float64(33.3421),
 np.float64(33.1317),
 np.float64(34.027),
 np.float64(32.8443),
 np.float64(32.0385),
 np.float64(34.4693),
 np.float64(31.4332),
 np.float64(32.6883),
 np.float64(31.4208),
 np.float64(32.7267),
 np.float64(33.0657),
 np.float64(33.314),
 np.float64(32.8341),
 np.float64(31.5678),
 np.float64(32.2194),
 np.float64(33.8659),
 np.float64(32.5153),
 np.float64(33.1273),
 np.float64(33.0672),
 np.float64(33.4296),
 np.float64(30.7935),
 np.float64(32.5777),
 np.float64(33.8356),
 np.float64(32.9445),
 np.float64(32.5303),
 np.float64(32.7401),
 np.float64(33.5906),
 np.float64(32.8532),
 np.float64(33.2087),
 np.float64(32.907),
 np.float64(33.3327),
 np.float64(32.4028),
 np.float64(32.4529),
 np.float64(33.3465),
 np.float64(33.3795),
 np.float64(31.4574),
 np.float64(32.896),
 np.float64(33.0011),
 np.float64(33.4063),
 np.float64(33.3197),
 np.float64(32.9289),
 np.float64(33.4353),
 np.float64(32.9126),
 np.float64(32.6738),
 np.float64(33.4293),
 np.float64(32.6064),
 np.float64(32.3385),
 np.float64(32.9673),
 np.float64(33.7264),
 np.float64(33.0318)]

In [ ]:
# Your code here