# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import pandas as pd
import numpy as np

# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents

In [2]:
# Run this code:
salaries = pd.read_csv('../data/Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [3]:
salaries.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

In [4]:
salaries.info()

<class 'pandas.DataFrame'>
RangeIndex: 33183 entries, 0 to 33182
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               33183 non-null  str
 1   Job Titles         33183 non-null  str
 2   Department         33183 non-null  str
 3   Full or Part-Time  33183 non-null  str
 4   Salary or Hourly   33183 non-null  str
 5   Typical Hours      8022 non-null   float64
 6   Annual Salary      25161 non-null  float64
 7   Hourly Rate        8022 non-null   float64
dtypes: float64(3), str(5)
memory usage: 2.0 MB

In [5]:
salaries.describe()

       Typical Hours  Annual Salary  Hourly Rate
count    8022.000000   25161.000000  8022.000000
mean       34.507604   86786.999790    32.788558
std         9.252077   21041.354602    12.112573
min        10.000000    7200.000000     2.650000
25%        20.000000   76266.000000    21.200000
50%        40.000000   90024.000000    35.600000
75%        40.000000   96060.000000    40.200000
max        40.000000  300000.000000   109.000000

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [6]:
hourly_workers: pd.DataFrame = salaries[salaries["Salary or Hourly"] == "Hourly"].drop(columns=["Annual Salary"])
hourly_workers.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Hourly Rate
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,19.86
6,"ABBATACOLA, ROBERT J",ELECTRICAL MECHANIC,AVIATION,F,Hourly,40.0,46.10
7,"ABBATE, JOSEPH L",POOL MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40.0,35.60
10,"ABBOTT, BETTY L",FOSTER GRANDPARENT,FAMILY & SUPPORT,P,Hourly,20.0,2.65
18,"ABDULLAH, LAKENYA N",CROSSING GUARD,OEMC,P,Hourly,20.0,17.68

In [7]:
from scipy import stats

alpha: float = 0.05
hourly_rates: pd.Series = hourly_workers["Hourly Rate"].dropna()
zstat, pval = stats.ttest_1samp(
    a=hourly_rates,
    popmean=30.0,
    nan_policy="omit",
    alternative="two-sided"
)
reject_h0: bool = pval < alpha

print(f"The null hypothesis is confidently rejected: {reject_h0} (p-value = {pval})")

The null hypothesis is confidently rejected: True (p-value = 4.3230240486230085e-92)

# Challenge 3 - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [8]:
ci = stats.t.interval(
    confidence=0.95,
    df=hourly_rates.__len__() - 1,
    loc=hourly_rates.mean(),
    scale=stats.sem(hourly_rates)
)
print(f"CI 95%: {ci[0].round(2)}$ - {ci[1].round(2)}$")

CI 95%: 32.52$ - 33.05$

# Challenge 4 - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [9]:
from statsmodels.stats.proportion import proportions_ztest

alpha: float = 0.05
h0_proportion: float = 0.25
n_obs: int = hourly_workers.__len__()
part_time_workers: int = (hourly_workers["Full or Part-Time"] == "P").sum()

zstat, pval = proportions_ztest(
    count=part_time_workers,
    nobs=n_obs,
    value=h0_proportion,
    alternative="two-sided"
)
reject_h0: bool = pval < alpha

print(f"The null hypothesis is confidently rejected: {reject_h0} (p-value = {pval.round(4)})")

The null hypothesis is confidently rejected: True (p-value = 0.0297)

# BONUS Challenge 1 - T-test

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_re`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](https://researchbasics.education.uconn.edu/t-test/) and [this Quora](https://www.quora.com/What-is-the-difference-between-a-paired-and-unpaired-t-test). Make sure you understand when to use which type of t-test.

In [10]:
# Import libraries

import pandas as pd
import numpy as np
from scipy import stats

#### Import dataset

In this challenge we will work on the Pokemon dataset you have used last week. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.).

In [11]:
# Import dataset
pokemon = pd.read_csv('../data/Pokemon.csv')
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [12]:
pokemon.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    str
 2   Type 1      800 non-null    str
 3   Type 2      414 non-null    str
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), str(3)
memory usage: 75.9 KB

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

In [13]:
def t_test_features(
        s1: pd.DataFrame,
        s2: pd.DataFrame,
        features: list[str] = [
            'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total'
        ],
    ):
    """Test means of a feature set of two samples
    
    Args:
        s1 (pd.DataFrame): sample 1
        s2 (pd.DataFrame): sample 2
        features (list[str]): an array of features to test
    
    Returns:
        dict (dict[str, np.float64]):
            a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    results: dict[str, np.float64] = {}

    for f in features:
        s1_f: pd.Series = s1[f]
        s2_f: pd.Series = s2[f]

        _, results[f] = stats.ttest_ind(
            a=s1_f,
            b=s2_f,
            nan_policy="omit",
            alternative="two-sided"
        )
    
    return results

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [14]:
legendary_pkmn: pd.DataFrame = pokemon[pokemon.Legendary == True]
normal_pkmn: pd.DataFrame = pokemon[pokemon.Legendary == False]

In [15]:
display(t_test_features(normal_pkmn, legendary_pkmn))

{'HP': np.float64(3.3306476848461905e-15),
 'Attack': np.float64(7.827253003205253e-24),
 'Defense': np.float64(1.5842226094427239e-12),
 'Sp. Atk': np.float64(6.314915770427278e-41),
 'Sp. Def': np.float64(1.8439809580409402e-26),
 'Speed': np.float64(2.3540754436898388e-21),
 'Total': np.float64(3.0952457469653014e-52)}

#### From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

-- Your comment here

Given extremely low p-values for all results, we can reject the null hypothesis and conclude that Legendary and non-Legendary pokemon do have significantly different stats on each feature.

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [16]:
first_gen_pkmn: pd.DataFrame = pokemon[pokemon.Generation == 1]
second_gen_pkmn: pd.DataFrame = pokemon[pokemon.Generation ==2]

In [17]:
display(t_test_features(first_gen_pkmn, second_gen_pkmn))

{'HP': np.float64(0.13791881412813617),
 'Attack': np.float64(0.24050968418101448),
 'Defense': np.float64(0.5407630349194361),
 'Sp. Atk': np.float64(0.14119788176331505),
 'Sp. Def': np.float64(0.16781226231606383),
 'Speed': np.float64(0.002835695481257868),
 'Total': np.float64(0.5599140649014442)}

#### What conclusions can you make?

-- Your comment here

Differently from the first scenario, we cannot reject the null hypothesis, so we cannot conclude that there is a significant difference in stats between Gen 1 and Gen 2 pokemon. The only exception to be made is that of **Speed**, which p-value of 0.002 is well below our threshold: for this stat specifically, the null hypothesis is rejected.

However, it is worth noting two things: first, the degree to which we can be confident in the null hypothesis is different for each stat, with some being higher (**Defense** being 0.54) and some lower (**Sp. Atk** being 0.14). Second, this result does not give us any information in regards to which generation has changed, or if changes are different for different stats. As for speed, we cannot know which generation is actually faster.

#### Compare pokemons who have single type vs those having two types.

In [18]:
single_type_pkmn: pd.DataFrame = pokemon[pokemon["Type 2"].isna()]
double_type_pkmn: pd.DataFrame = pokemon[pokemon["Type 2"].notna()]

In [19]:
display(t_test_features(single_type_pkmn, double_type_pkmn))

{'HP': np.float64(0.1106064314443184),
 'Attack': np.float64(0.00015741395666164407),
 'Defense': np.float64(3.250594205756991e-08),
 'Sp. Atk': np.float64(0.0001454917404035149),
 'Sp. Def': np.float64(0.00010893304795534405),
 'Speed': np.float64(0.02405141079403747),
 'Total': np.float64(1.1749035008828765e-07)}

#### What conclusions can you make?

-- Your comment here

Once again, the results from the t-test about pokemon types successfully rejects the null hypothesis. All p-values are considerably lower than the significance threshold. This means that there is a significant difference in stats between pokemn with 1 an 2 types (again, though, we cannot determine from this alone in which way this difference exists). The only exception is the stat **HP**, which we cannot confidently say differs between the two types - though the result is only barely above the threshold.

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [20]:
# N.B. (vis-a-vis hint): here we are comparing results of the same population "pokemon",
# therefore, we will use a correlated t_test, since we compare stats of the same pokemon (hence paired t-test)

In [21]:
_, attack_defense_pval = stats.ttest_rel(
    a=pokemon.Attack,
    b=pokemon.Defense,
    nan_policy="omit",
    alternative="two-sided"
)

print(f"Reject that Pokemon Attack and Defense have no significant difference: {attack_defense_pval < 0.05}")
print("P-value:", attack_defense_pval)

Reject that Pokemon Attack and Defense have no significant difference: True
P-value: 1.714030347935858e-05

In [22]:
_, spatk_spdef_pval = stats.ttest_rel(
    a=pokemon["Sp. Atk"],
    b=pokemon["Sp. Def"],
    nan_policy="omit",
    alternative="two-sided"
)

print(f"Reject that Pokemon Sp. Atk and Sp. Def have no significant difference: {spatk_spdef_pval < 0.05}")
print("P-value:", spatk_spdef_pval)

Reject that Pokemon Sp. Atk and Sp. Def have no significant difference: False
P-value: 0.3933685997548119

#### What conclusions can you make?

-- Your comment here
We can reject the null hypothesis that there is no significant difference between Pokemon attack and defense stats, but we cannot reject it for sp. atk and sp. def - from our findings we cannot say that a difference exists.